### ISSUE TITLE
Remove better-sqlite3 dependency by exporting the data as JSON?

### ISSUE THREAD

**Issue by soulgalore** [thegreenwebfoundation/co2.js#20]
Hi @mrchrisadams so I think I was wrong about using sqlite. In my case for sitespeed.io it adds a lot of overhead when I install sitespeed.io. Building the extra dependencies with node-gyp is slow. And I also think it makes co2.js dirtier for others to use. 

My mine concern is privacy. Actually the exported database could be only the domain name in a fat JSON file? That would probably gzip quite ok. The SQL lite database is 16 mb and I think a plain simple JSON just hold the domains could be a couple of mb, I can have a look and check if there's a way to do it smarter. The users of the API could get as much info as you have, and co2.js users will just get the correct co2 number?

**Comment by mrchrisadams** [comment]
Hi Peter! 

Given the use we're making right now, I think there's a few directions we could go in.

## Represent just the data structure we use right now for querying

Right now, we're using SQLite to do a look up to see if the given url is the database, and just returning true or false. 

We could probably pare this back down to Set, which I think we'd need to represent as an Array of strings in JSON. That would be the smallest, fast way I can think of to support the current pattern of accessing data.

So, we'd maybe load something like `green-domains.json`, or if we cared about file size after installation, store it as `green-domains.json.gz` and use node's native support of gzip to decompress it at startup. I think node packages are compressed when we upload them, so this would only save space after it had been downloaded.

You cold make it even smaller, because the domains just resolve to IP addresses, and theoretically we could simply just have a list of numbers ranges to represent these IP ranges, and rely on doing a DNS lookup to see if a given domain name resolves to a specific IP address.

The downside of this is that we'd make loads of DNS lookups, which could be slow. But then again for the sitespeed use-case, we will have already made them anyway.

I think the compressed JSON array, to be loaded in, and treated like a `Set`, or even just 'queried' using `indexOf` would give us the responses we currently rely on.

## Provide the flexibility but lose the need for node-gyp compiling

The current dataset has a bit more info than just true or false. It also includes the time of the last check, and also the underlying organisation doing the hosting. Having this can be useful, but we're not using it sitespeed.

I looked through this list for alternative, pure nodejs versions, and there a bunch of stores that would allow for the same querying, but most are either no-longer maintained or hold everything in memory

https://stackoverflow.com/questions/6493382/recommend-database-in-pure-node-js-with-no-dependencies#6494876

There's one that looks promising, and it includes indexing, which others don't. As far as I can tell though, it indexes things by storing everything in memory!

https://github.com/louischatriot/nedb

## Use a package that provides a precompiled version of SQLite:

It looks like Mapbox also distribute software that relies on sqlite, and they get around this by providing pre-compiled versions of sqlite, for common systems.

https://github.com/mapbox/node-sqlite3/wiki/Binaries

We'd need to adjust the API slightly to use their API, but a quick look suggests it's not a huge departure from better sqlite.

https://cldellow.com/2018/06/22/sqlite-parquet-vtable.html

**Comment by mrchrisadams** [comment]
Okay, using the precompiled version does speed up the build on Travis, taking it from around 5 minutes total, to 2 and a half minutes total:

|build|link|time|
|----|---|---|
|compile on install| https://travis-ci.org/thegreenwebfoundation/co2.js/builds/657707157| 2 min 40 sec|
|precompiled| https://travis-ci.org/thegreenwebfoundation/co2.js/builds/659772022| 4 min 53 sec|

If we used this, we'd need to change the API to use the other SQLite library as there are some small differences in how you execute queries.

### My preferred option:

I think being able to run queries and see data is useful, but I totally understand the privacy and complexity angle.

I'd be happiest with being able to keep publishing SQLite datasets, as I think changing the method calls would be the smallest amount of work and means updating in future doesn't change too much.

Other consumers of the dataset, like the privacy protecting search enginge Searx, also consume the same SQLite dataset.

From my POV, I'm in favour of only one dataset, and file format to keep track of, and [SQLite is recognised as a good, archival format](https://www.loc.gov/preservation/digital/formats/fdd/fdd000461.shtml).

### A middle ground option for sitespeed

One approach we could take is to have a task to generate this smaller JSON file of just the green domains as part of the release process for either sitespeed, or this CO2 module.

As part of a release process we might have something like _generateGreenDomainListJSON_ as a npm task, and include _that_ JSON file, rather than the entire SQLite dataset that we do now. that 

https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/sustainable/index.js#L84

What do you think?

**Comment by soulgalore** [comment]
Yes the middle ground would work but it also means we need to get rid of the sqlite dependency in co2.js? For me that dependency  kind of dirty because it will add upp on the dependency tree, and for sitespeed.io users I think either use the json or configure to use the API is just fine. And I think to make other tools also adopt co2.js, it will be easier if it just depend on debug? That way it's easy to just drop in the dependency and then use the API for freshest and best figures.

So for me one that means drop sqlite support in CO2.js, keep the methods where you could add your own array with green domains (meaning we could have somekind if list directly in sitespeed.io as you said). But for normal usage of co2.js you would use the API. Is that also what you mean? :)

The coming week I'll try to minimise dependencies in sitespeed.io and make the container more slim, it has grown the last months and makes it impossible to run on small cloud instances. Making co2.js clean is part of It but there are also other things I need to clean.

I think in your process of creating the SQLLite database, you could probably also automate to generate a JSON for simpler use cases. But that could be next step, I could help you with that if you want.

Looking at the data in the database I wonder if it would be possible to also introduce wildcard matchning for subdomains?  Or would that be too big risk to give wrong numbers? There's a tool to categorise third party domains (to know what tool/company and their structure looks like this: https://github.com/patrickhulce/third-party-web/blob/master/data/entities.json5 
That would of course be a lot of work :)

**Comment by mrchrisadams** [comment]
Hmm… the more we discuss this, the more it makes me think that having separate modules on npm makes sense.

One with the database and sqlite, and one with the slimmed down code as described here, for including in stuff like sitespeed and so on.

**Comment by mrchrisadams** [comment]
I'll likely spend a bit of time tomorrow on making these smaller modules, and submit a PR for you to look over.

Thanks amigo 👍

**Comment by soulgalore** [comment]
Cool. I think there's one more issue that would help when its moved. Now you need have `python `and `make` installed to install co2.js. That works fine on your local dev machine but if you wanna do it in a slim Docker container you need to install python/build-essential to install co2.js. Not a super big deal but for example sitespeed.io works without those dependencies today. Let me know if there's anything I can do to help!

**Comment by mrchrisadams** [comment]
Hey @soulgalore, I think that's down to needing to compile sqlite from `better-sqlite`.

If I get rid of that, proceed with the separate sqlite-based npm package, and replace it with the JSON list of domains, I think that would remove the pythonic dependencies.

That sound about right to you?

**Comment by soulgalore** [comment]
Yes perfect :D

**Comment by mrchrisadams** [comment]
OK, there's now a url2green module, that for the time being has the database and the JSON packaged in that you might need to run queries against. 

You can use this JSON in this co2 package.

I'm keeping it out of this npm package for the time being - I think it's better to have a stable url to always be able to fetch the latest snapshot from, and I'm working on this next.

https://www.npmjs.com/package/@tgwf/url2green

I've also created a PR which removes the dependency on any sqlite library

https://github.com/thegreenwebfoundation/co2.js/pull/22

**Comment by soulgalore** [comment]
Great lets close this now!
