### ISSUE TITLE
1byte model values

### ISSUE THREAD

**Issue by mstaschik** [thegreenwebfoundation/co2.js#32]
in the [1byte.js](https://github.com/thegreenwebfoundation/co2.js/blob/master/src/1byte.js) your parameters are:

const KWH_PER_BYTE_IN_DC = 0.00000000072;
const KWH_PER_BYTE_FOR_NETWORK = 0.00000000488;

In the [1byte model](https://theshiftproject.org/wp-content/uploads/2019/10/Lean-ICT-Materials-Liens-%C3%A0-t%C3%A9l%C3%A9charger-r%C3%A9par%C3%A9-le-29-10-2019.pdf) the values are:

7,20E-11 ==> 0.000000000072 (1 more zero)
4,29E-10 ==> 0,000000000429

This is what I don't understand.

**Comment by mrchrisadams** [comment]
Hmm… I think that was an error on my part - sheesh 🤦 .

I'll push a new version tomorrow, and update the changelog accordingly - thanks for flagging this.

I also think it's might be better to use this `000_000_000_072` kind of notation in future, or the `7.2e-11` than all those zeros, as they're both valid javascript, and much more readable.

If you wanted to make a pull request with this change, I'd be very grateful, and I'd like to mention in you the release notes for the next release :)

BTW, there's been an update since 2019 - on this, that's worth being aware of. I haven't updated any of this to take it into account, but I think it would be worthwhile looking into in the coming days. Anyway, thanks again.

https://www.carbonbrief.org/factcheck-what-is-the-carbon-footprint-of-streaming-video-on-netflix
https://theshiftproject.org/en/article/shift-project-really-overestimate-carbon-footprint-video-analysis/

**Comment by mrchrisadams** [comment]
**Note to self:** I realise this observable notebook below was using the wrong values too (I've now updated it). For all I can remember I might have actually copied it from that notebook into the js file back in 2019.

It would likely make sense to use the npm package in case others stumble across this.

https://observablehq.com/@mrchrisadams/carbon-footprint-of-sending-data-around

**Comment by mstaschik** [comment]
Hi Chris, thank your for the quick response and the fix! :-)

**Comment by jepster-dk** [comment]
@mrchrisadams, is this something that's been merged and deployed yet somewhere?

**Comment by mrchrisadams** [comment]
@ada-ada-ada-art you can download this with the fix from npm - co2.js 0.8.0 should now include it. Thanks again for raising the issue 💚
