### ISSUE TITLE
Default carbonIntensity checking fallbacks

### ISSUE THREAD

**Issue by drydenwilliams** [thegreenwebfoundation/co2.js#76]
I've seen there have been changes to the SWD method which have been suddenly merged in. Why is this? Can it go in PR review beforehand? Some of the additions are a little confusing. And seemingly change the calculations quite a bit.

1. Why do we need this logic? We have a default value set `carbonIntensity = GLOBAL_INTENSITY` so it will fall back to global intensity anyway. https://github.com/thegreenwebfoundation/co2.js/blob/95939c3abb6116778ba2568c7f6417d5205987e8/src/sustainable-web-design.js#L100
2. Why does it fall back if `true` to `RENEWABLES_INTENSITY`?
https://github.com/thegreenwebfoundation/co2.js/blob/95939c3abb6116778ba2568c7f6417d5205987e8/src/sustainable-web-design.js#L105
3. Why has `energyPerVisit` changed? It doesn't meet the calculations in [SWD](https://sustainablewebdesign.org/calculating-digital-emissions/) page
https://github.com/thegreenwebfoundation/co2.js/blob/95939c3abb6116778ba2568c7f6417d5205987e8/src/sustainable-web-design.js#L190

Before we make breaking changes like this we need to go through them together and make sure they all align and importantly we understand the why and what is outputted. 

I wouldn't add any more updates/code without adding TypeScript too.

**Comment by drydenwilliams** [comment]
When did `co2byComponent`, `energyPerByteByComponent`, `perByte` get merged in? @mrchrisadams

**Comment by mrchrisadams** [comment]
hi Dryden,

> When did co2byComponent, energyPerByteByComponent, perByte get merged in?

See PR #67 - about three weeks back.

https://github.com/thegreenwebfoundation/co2.js/pull/67/

These changes were designed to allow support for existing clients, like sitespeed, and lighthouse.

There's some discussion about adding this to the HTTP Archive runs, which may need to consume HAR files of the loaded pages, rather than doing a re-run of all the millions of pages crawled as part of the HTTP Archive regular crawl.

> Why do we need this logic?

In see issue #56  back in December I tagged you to ask a few questions about supporting other clients , and asked for these methods, explaining why they were needed. These provide an upgrade path for existing clients, so they can adopt the SWD model from consuming the current model based on the 1byte calculations from before.

I hadn't heard back, and they were needed, so I ended up implementing them myself. Sorry about not tagging you on the previous PR - I'll tag you in future when there are future PR, and I think this highlights the need to have a better documented process for handling future changes.

https://github.com/thegreenwebfoundation/co2.js/issues/56

I'm not available today for more discussion but I'm happy to chat next week in more detail.

In the meantime, I've shared a jupyter notebook with you (the nextjournal one) going more detail about how the SWD model relates to the underlying paper it's based on.

I've also got the go-ahead to share it in a slightly edited form to add to this repo. I think this could provide a useful addition to the documentation we have so far, outlining where we might work on future versions of the SWD model as new data becomes available.

Have a nice weekend - I hope this is enough for now - I'll pick this up next week.

> I wouldn't add any more updates/code without adding TypeScript too

There's an existing PR here that started a conversion:

https://github.com/thegreenwebfoundation/co2.js/pull/30

…but it's pretty old now, and I had held off merging it before because I didn't know well Typescript all that well.

My main worry about Typescript is that its a big language and introducing a bunch of Typescript's features might raise the bar for contribution so that only people who know typescript really well can do so.

I think that would reduce adoption, but I don't know enough about Typescript to really tell either way right now.

There's an issue, #77, linked below for more discussion - can we discuss it and share any links to public PRs there please?

https://github.com/thegreenwebfoundation/co2.js/issues/77

**Comment by fershad** [comment]
This issue seems to be resolved/is dated. 
@mrchrisadams I'm going to mark it as closed.
